# -*- coding: utf-8 -*-
"""Shared public-safe e-mail utilities."""

from __future__ import annotations

import os
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Iterable

import pandas as pd


def dataframe_to_html_table(df: pd.DataFrame, max_rows: int = 200) -> str:
    if df.empty:
        return "<p>No records found.</p>"

    shown = df.head(max_rows).copy()
    return shown.to_html(index=False, border=0, escape=False, classes="data-table")


def wrap_email_html(title: str, body_html: str) -> str:
    return f"""
    <html>
      <head>
        <style>
          body {{ font-family: Calibri, Arial, sans-serif; font-size: 14px; color: #111827; }}
          .container {{ max-width: 960px; }}
          .data-table {{ border-collapse: collapse; width: 100%; }}
          .data-table th {{ background: #1f2937; color: #ffffff; padding: 8px; text-align: left; }}
          .data-table td {{ border: 1px solid #e5e7eb; padding: 7px; }}
          .muted {{ color: #6b7280; font-size: 12px; }}
        </style>
      </head>
      <body>
        <div class="container">
          <h2>{title}</h2>
          {body_html}
          <p class="muted">Generated by Financial Automation Suite - public-safe template.</p>
        </div>
      </body>
    </html>
    """


def send_smtp_email(to: Iterable[str], subject: str, html_body: str, cc: Iterable[str] | None = None) -> None:
    """
    Sends an e-mail using SMTP configuration from environment variables.

    This function is public-safe: no credentials are hardcoded.
    """
    smtp_server = os.getenv("SMTP_SERVER", "")
    smtp_port = int(os.getenv("SMTP_PORT", "465"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASS", "")

    if not all([smtp_server, smtp_user, smtp_pass]):
        raise EnvironmentError("SMTP_SERVER, SMTP_USER and SMTP_PASS must be configured.")

    recipients = list(to) + list(cc or [])

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = ", ".join(to)
    if cc:
        msg["Cc"] = ", ".join(cc)

    msg.attach(MIMEText(html_body, "html", "utf-8"))

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(smtp_server, smtp_port, context=context) as server:
        server.login(smtp_user, smtp_pass)
        server.sendmail(smtp_user, recipients, msg.as_string())
